// server actions end in _RESPONSE
export const Actions = {
  ADD_GUEST: 'ADD_GUEST',
  ADD_GUEST_RESPONSE: 'ADD_GUEST_RESPONSE',
  COMPLETE_GUEST: 'COMPLETE_GUEST',
  COMPLETE_GUEST_RESPONSE: 'COMPLETE_GUEST_RESPONSE',
  GET_GUESTS: 'GET_GUESTS',
  GET_GUESTS_RESPONSE: 'GET_GUESTS_RESPONSE',
  NOTIFY_GUEST: 'NOTIFY_GUEST',
  NOTIFY_GUEST_RESPONSE: 'NOTIFY_GUEST_RESPONSE',
  SET_VIEW: 'SET_VIEW',
  UPDATE_NOTIFY_MESSAGE: 'UPDATE_NOTIFY_MESSAGE',
};

export const Defaults = {
  DEFAULT_NOTIFY_MESSAGE: 'You have been notified!',
};

export const ViewFilters = {
  CURRENT_GUESTS: 'CURRENT_GUESTS',
  COMPLETED_GUESTS: 'COMPLETED_GUESTS',
};

