// server actions end in _RESPONSE
export const QueueConstants = {
  ADD_GUEST: 'ADD_GUEST',
  ADD_GUEST_RESPONSE: 'ADD_GUEST_RESPONSE',
  GET_GUESTS: 'GET_GUESTS',
  GET_GUESTS_RESPONSE: 'GET_GUESTS_RESPONSE',
  NOTIFY_GUEST: 'NOTIFY_GUEST',
  NOTIFY_GUEST_RESPONSE: 'NOTIFY_GUEST_RESPONSE',
  COMPLETE_GUEST: 'COMPLETE_GUEST',
  COMPLETE_GUEST_RESPONSE: 'COMPLETE_GUEST_RESPONSE',
};

